-- Staging-only, single-POST representative evidence ledger. This migration
-- creates no run row: an operator must first freeze actual authoritative job,
-- product, subject and reference metadata with the read-only preflight query.
CREATE TABLE IF NOT EXISTS normal_representative_evidence_runs (
  task_id TEXT PRIMARY KEY,
  idempotency_key TEXT NOT NULL UNIQUE CHECK (idempotency_key ~ '^[0-9a-f]{64}$'),
  job_id TEXT NOT NULL UNIQUE REFERENCES jobs(id),
  user_id TEXT NOT NULL REFERENCES users(id),
  product_id TEXT NOT NULL REFERENCES products(id),
  subject_id TEXT NOT NULL,
  reference_sha256 TEXT NOT NULL CHECK (reference_sha256 ~ '^[0-9a-f]{64}$'),
  reference_manifest_sha256 TEXT NOT NULL CHECK (reference_manifest_sha256 ~ '^[0-9a-f]{64}$'),
  reference_brand TEXT NOT NULL CHECK (length(trim(reference_brand)) > 0),
  authorization_source TEXT NOT NULL CHECK (authorization_source='approved_reference_manifest:v2'),
  product_snapshot_sha256 TEXT NOT NULL CHECK (product_snapshot_sha256 ~ '^[0-9a-f]{64}$'),
  deploy_sha TEXT NOT NULL CHECK (deploy_sha ~ '^[0-9a-f]{40}$'),
  model TEXT NOT NULL CHECK (model='dreamina-seedance-2-0-mini-260615'),
  category TEXT NOT NULL CHECK (length(trim(category)) > 0),
  format TEXT NOT NULL CHECK (format='talking_head'),
  duration_s INTEGER NOT NULL CHECK (duration_s=15),
  resolution TEXT NOT NULL CHECK (resolution='720p'),
  estimated_cost_usd NUMERIC(8,4) NOT NULL CHECK (estimated_cost_usd=1.134),
  max_cost_usd NUMERIC(8,4) NOT NULL CHECK (max_cost_usd=1.25),
  provider_post_count INTEGER NOT NULL DEFAULT 0 CHECK (provider_post_count BETWEEN 0 AND 1),
  state TEXT NOT NULL DEFAULT 'PREPOST_READY' CHECK (state IN
    ('PREPOST_READY','POST_ATTEMPTED','TASK_BOUND','PROVIDER_SUCCEEDED','CAPTURED_NO_PUBLICATION','STOP_NO_RETRY')),
  payload_sha256 TEXT CHECK (payload_sha256 IS NULL OR payload_sha256 ~ '^[0-9a-f]{64}$'),
  provider_task_id TEXT UNIQUE,
  provider_usage_json TEXT,
  actual_cost_usd NUMERIC(8,4) CHECK (actual_cost_usd IS NULL OR actual_cost_usd <= 1.25),
  qc_json TEXT,
  artifact_key TEXT CHECK (artifact_key IS NULL OR artifact_key LIKE 'private/evidence/%'),
  retrieval_sha256 TEXT CHECK (retrieval_sha256 IS NULL OR retrieval_sha256 ~ '^[0-9a-f]{64}$'),
  correlation_json TEXT,
  redaction_verified BOOLEAN NOT NULL DEFAULT FALSE,
  stop_reason TEXT,
  post_attempted_at TEXT,
  task_bound_at TEXT,
  provider_succeeded_at TEXT,
  captured_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (provider_post_count=0 OR state<>'PREPOST_READY'),
  CHECK (provider_task_id IS NULL OR provider_post_count=1),
  CHECK (state NOT IN ('TASK_BOUND','PROVIDER_SUCCEEDED','CAPTURED_NO_PUBLICATION') OR provider_task_id IS NOT NULL),
  CHECK (state<>'CAPTURED_NO_PUBLICATION' OR (artifact_key IS NOT NULL AND retrieval_sha256 IS NOT NULL AND qc_json IS NOT NULL AND correlation_json IS NOT NULL AND redaction_verified))
);
